version: "3.9"
services:
  demo-app:
    image: spring-boot-demo:latest
    restart: always
    ports:
      - 80:8080
    environment:
      DB_USER: "user"
      DB_PASSWORD: "secret"
      DB_URL: jdbc:postgresql://database:5432/hero
    depends_on:
      - database

  database:
    image: postgres:15.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hero
